version: "2"
services:
    openvpn-client:
        image: yacht7/openvpn-client            
        container_name: openvpn-client
        cap_add:
            - NET_ADMIN                         
        environment: 
            - KILL_SWITCH=true                  
            - FORWARDED_PORTS=57154             
        devices:
            - /dev/net/tun                      
        volumes:
            - /volume1/docker/mullvadVPN/config/mullvad_config_linux_it_mil:/data/vpn   
        ports:
            - 8080:8080                         # qbittorrent
            - 7878:7878                         # radarr
            - 9117:9117                         # jackett
            - 8989:8989                         # sonarr
            - 6881:6881                         #?
            - 6881:6881/udp                     #?
        restart: unless-stopped
 
    qbittorrent:
        image: linuxserver/qbittorrent
        container_name: qbittorrent
        environment:
            - PUID=1024
            - PGID=101
            - TZ=Europe/Rome
            - UMASK_SET=022
            - WEBUI_PORT=8080
        volumes:
            - /volume1/docker/qbittorrent/config:/config
            - /volume1/video/downloads/complete:/completedownloads
            - /volume1/video/downloads/incomplete:/incompletedownloads
        network_mode: service:expressvpn
        restart: unless-stopped

    jackett:
        image: linuxserver/jackett
        container_name: jackett
        environment:
            - PUID=1024
            - PGID=101
            - TZ=Europe/Rome
            - AUTO_UPDATE=true
        volumes:
            - /volume1/docker/jackett/config:/config
        restart: unless-stopped
        network_mode: service:expressvpn
        depends_on:
            - qbittorrent

    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        environment:
            - PUID=1024
            - PGID=101
            - TZ=Europe/Rome
        volumes:
            - /volume1/docker/sonarr/config:/config
            - /volume1/video/Shows/Inglese:/tv
            - /volume1/video/downloads/complete:/downloads
        ports:
            - 8989:8989
        restart: unless-stopped
        network_mode: service:expressvpn
        depends_on:
            - jackett
            - qbittorrent

    radarr:
        image: linuxserver/radarr
        container_name: radarr
        environment:
            - PUID=1024
            - PGID=101
            - TZ=Europe/Rome
        volumes:
            - /volume1/docker/radarr/config:/config
            - /volume1/video/Movies/Inglese:/movies
            - /volume1/video/downloads/complete:/downloads
        ports:
            - 7878:7878
        restart: unless-stopped
        network_mode: service:expressvpn
        depends_on:
            - jackett
            - qbittorrent

    plex:
        container_name: plex
        image: linuxserver/plex
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/dri:/dev/dri
        privileged: true
        environment:
            PGID: '101'
            PUID: '1024'
            VERSION: docker
        network_mode: host
        restart: unless-stopped
        volumes:
            - /volume1/docker/plex/config:/config:rw
            - /volume1/video/Movies/Inglese:/Film_Inglese:rw
            - /volume1/video/Movies/Italiano:/Film_Italiano:rw
            - /volume1/video/Shows/Inglese:/SerieTV_Inglese:rw
            - /volume1/video/Shows/Italiano:/SerieTV_Italiano:rw
